"""Add stripe_account_id to users

Revision ID: 0810ee77e4ff
Revises: 15228c8f0f33
Create Date: 2026-05-24 09:41:40.045959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0810ee77e4ff'
down_revision: Union[str, Sequence[str], None] = '15228c8f0f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###
