"""Add is_cron_active to jobs

Revision ID: fc12c8874c3b
Revises: caf7061a4f13
Create Date: 2026-05-24 00:01:40.210874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc12c8874c3b'
down_revision: Union[str, Sequence[str], None] = 'caf7061a4f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_cron_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_cron_active')
    # ### end Alembic commands ###
